### ISSUE TITLE
RootMargin doesn't seem to be working

### ISSUE THREAD

**Issue by SudharsanSukumar** [thebuilder/react-intersection-observer#207]
Hi again,

I'm working on more virtualization and noticed that the root margin doesn't seem to be working (inview only true when the container is actually in view). I've set it to 500px. Tested in Chrome and FireFox.

I think this might not be an issue with this package but was curious if you've seen / run into this before.

Also, I noticed that dist no longer contains an unminified umd file. It doesn't have a big impact on us but was curious what the reason was.

Thanks,
Dharsan

**Comment by thebuilder** [comment]
Do you have an example of this issue? Maybe create a codesandbox🙂

I can't really see a use case for the unminified umd bundle. It should just be one url you can reference. It does provide a sourcemap, so you can still debug it in the browser. I'm not personally using umd packages, so let me know if it's something that's actually needed.

**Comment by thebuilder** [comment]
I looked at the `rootMargin`, and is working as it should.
If you are running into issues, it most likely because you are using a custom `root`, and the CSS is causing the bounds to be calculated incorrectly.
The current Storybook example actually contains this exact problem:
https://thebuilder.github.io/react-intersection-observer/iframe.html?id=intersection-observer--with-root-and-rootmargin

The example has a `rootMargin` of `64px`, but it triggers when the element is going into the viewport. However, if you remove the surrounding `padding: 64px;`, it will trigger correctly before going into the view.

I'll add some more examples to the Storybook.

**Comment by SudharsanSukumar** [comment]
Great thanks for the help!
