### ISSUE TITLE
inView returns false for visible elements on first render

### ISSUE THREAD

**Issue by andy-hook** [thebuilder/react-intersection-observer#284]
inView returns `false` for **visible** elements on the initial render, is this expected behaviour? you can clearly see this when quickly switching back and forth on the "Start in view" story.

Logging `entry` on first render returns `undefined`

**Comment by thebuilder** [comment]
It's the expected behavior. The `ref` needs to be set be set before it's able to determine the intersection state, so the application needs to do an initial render pass.

You can look at `entry` to see if the IntersectionObserver has been initialized - this can be used to delay rendering either state until you know it's been correctly determined.

**Comment by andy-hook** [comment]
I thought this might be the case, really appreciate you responding so quickly. Thank you for all of your work on this package, it's really helpful.

**Comment by grazianodev** [comment]
I have a similar issue, I would like to execute a callback if the element whose visibility I'm tracking is 
already in the viewport on the initial render:

```
const [ ref, inView, entry ] = useInView({ triggerOnce: true })

useEffect( () => {
    if( ! posts && inView ) handleFetchPosts()
}, [ inView ] )

return <div className="has-posts-list" ref={ ref }>{ postsList }</div>
```

This is currently not working as inView is `false` on first render. I didn't quite understand from your answer to @andy-hook if it is possible to work around this, and how... Sorry, not a Javascript expert here!

**Comment by andy-hook** [comment]
> I have a similar issue, I would like to execute a callback if the element whose visibility I'm tracking is
> already in the viewport on the initial render:
> 
> ```
> const [ ref, inView, entry ] = useInView({ triggerOnce: true })
> 
> useEffect( () => {
>     if( ! posts && inView ) handleFetchPosts()
> }, [ inView ] )
> 
> return <div className="has-posts-list" ref={ ref }>{ postsList }</div>
> ```
> 
> This is currently not working as inView is `false` on first render. I didn't quite understand from your answer to @andy-hook if it is possible to work around this, and how... Sorry, not a Javascript expert here!

You need to add `inviewEntry` to your `useEffect` dependency so that the block runs again as soon as it's available. 

See my usecase here – https://github.com/andy-hook/andyhook.dev/blob/145fdae454b309da262e49f7d4eeb39309609764/src/hooks/page-transition.tsx#L126

**Comment by grazianodev** [comment]
Thanks for your help! 

As it turns out my problem was actually more trivial. Since I was fetching some posts asynchronously I was rendering a spinner which was placed outside the element I was tracking, and that's why the inView callback was not being called. Once I've fixed that, the code I've originally posted was working well, so the element is "recognized" as visible on first render too. Just for the record.

**Comment by andy-hook** [comment]
Glad you figured it out!
