### ISSUE TITLE
Is wrapping element really required

### ISSUE THREAD

**Issue by TxHawks** [thebuilder/react-intersection-observer#47]
I feel like that `tag` prop should be optional, i.e., not with a default value, really optional, for only the cases the user actually needs a wrapping element.

**Comment by thebuilder** [comment]
@TxHawks **IntersectionObserver** needs a DOM node to work, which is why the tag is needed - also to make it as easy to use as possible. It would require a rewrite/alternative rendering method that would require the user to pass set the correct ref. 

Because there's no styling, and you can pass all the normal DOM attributes to the `div`, i don't see the need to support a user provided `ref`. There's also support for `innerRef` so you can get the `ref` if you need it for DOM interaction in your own component.

Is there a usecase i'm not seeing, other than *keep the DOM flat*?

**Comment by TxHawks** [comment]
Just keeping the DOM flat. And I do see your point

**Comment by thebuilder** [comment]
After working with render props that use ref passing, i've added support for creating the wrapping element yourself. See #69
