### ISSUE TITLE
onChange as an option for hooks

### ISSUE THREAD

**Issue by fandy** [thebuilder/react-intersection-observer#511]
Currently the only way to do something when the visibility changes is through the render API, and not hooks API. Although you _can_ work around this with some additional boilerplate, it'd be good to do something like: 

```
const { ref: mastheadRef, inView: mastheadVisible } = useInView({
    initialInView: true,
    onChange: (inView) => {
      console.log("in view");
      if (inView) {
        setMastheadVisible(true);
      }
    },
  });```

**Comment by thebuilder** [comment]
An issue with this, is the `onChange` would need to be an `useCallback` function, otherwise it would change on every render and cause the IntersectionObserver to be recreated. Since this can't be enforced, I'd much rather not open up the possibility to begin with - The `useEffect` method is the safest way. If you need to know before rendering, you can check the value during the render loop, maybe by comparing it with a `usePrevious` or  `useRef` hook.

If you need the `onChange` functionality, stick with the `<InView>` component where it's already supported and won't have this issue.

**Comment by thebuilder** [comment]
Thinking a bit more about this. The hook can store a ref to the onChange function, so it can call the current instance, without changing the ref callback. 

I can see how this would make sense for reducing boilerplate, e.g. when needing to do impression tracking.
