### ISSUE TITLE
InView component not respecting rootMargin?

### ISSUE THREAD

**Issue by bduffany** [thebuilder/react-intersection-observer#534]
See this codesandbox example:

https://codesandbox.io/s/adoring-kate-gzmcxb?file=/src/App.tsx

The first component in this example uses an intersection observer that triggers whenever the blue div's bottom position + 100px margin is no longer in view. (When triggered, the timestamp shown at the top of the scrolling element gets updated)

The second component uses `<InView />` for the same task (detecting when the margin is no longer in view). The intersection observer params and element layout are otherwise identical (except for the wrapper element created by `<InView>` itself). But this second component seemingly doesn't respect the 100px margin -- it passes `inView: false` when the margin area is still in view.

Is this intentional? If so, is there another way to detect when the scrollable element crosses the margin?

**Comment by thebuilder** [comment]
Seems like you aren't setting the ref correctly? It's `null`. Remember that that setting a `ref` doesn't trigger a rerender, and you only get refs after the first render - You have to change your state for that (which you do in the other example). The `<InView>` component contains the state, so it wouldn't trigger an update in the parent component. You can also use the `useInView` hook instead, since that force a second render when the IntersectionObserver runs.

I have demos in the Storybook for `<InView>` with `rootMargin`, and with `root` and `rootMargin`.
https://react-intersection-observer.vercel.app/?path=/story/inview-component--with-root-margin
