### ISSUE TITLE
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by davbrito** [thebuilder/react-intersection-observer#560]
**Describe the bug** A clear and concise description of what the bug is.
I'm using react-scripts v4.0.3 and I start gettign a compilation error when I upgrade to react-intersection-observer v9.3.0

**Expected behavior** A clear and concise description of what you expected to
happen.

It should compile normally

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/39559632/173694988-cc2b2866-6b86-4fba-9a08-29ba526da2fc.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Xubuntu

**Comment by michaelrodov** [comment]
facing the same issue. please help

**Comment by michaelrodov** [comment]
OS: iOS
Browser: edge
version: 102

**Comment by thebuilder** [comment]
https://github.com/facebook/create-react-app/issues/10356 Seems to be an issue with how CRA handles exports.

**Comment by thebuilder** [comment]
Running it locally with CRA 5.0.1, and seems to load fine?
The Codesandbox is also running with `react-scripts` 5.0.1 and is also working.

**Comment by michaelrodov** [comment]
import { useInView } from 'react-intersection-observer';

**Comment by michaelrodov** [comment]
import { useInView } from 'react-intersection-observer';
same as it was on the previous version. (8.32.0)

**Comment by thebuilder** [comment]
What version of Node.js are you using? This happens during bundling, so the browser doesn't matter.

**Comment by EMCarlos** [comment]
Ok! the version is v14.18.0

**Comment by michaelrodov** [comment]
im on node 12.18.3

**Comment by michaelrodov** [comment]
just tried now with node 16... same thing

**Comment by thebuilder** [comment]
> Having the same issue, I'm using react-scripts v4.0.3 and getting the same error on the react-intersection-observer v9.1.0. Tried to upgrade to v9.3.3 but still happens:
> 
> `Failed to compile.`
> 
> `./node_modules/react-intersection-observer/react-intersection-observer.mjs` `Can't import the named export 'Component' from non EcmaScript module (only default export is available)`
> 
> OS: Windows Browser: chrome Version: Version 102.0.5005.115

Just to be clear - You got this with `react-intersection-observer` version 9.1.0?

**Comment by thebuilder** [comment]
As far as I can tell, this issue is most likely caused by the Create React App environment you are using, and seems to be a common issue other libraries are running. This library should be exposing the output files in the correct manner, that various build tools can parse.

I think it's interesting you are seeing this specific error, since `react-intersection-observer` isn't exporting `Component` - Might be `React.Component`  it is referring to?

``` 
Can't import the named export 'Component' from non EcmaScript module (only default export is available)
``` 

I'd recommend you dig more into it, maybe try different suggested solutions in other Github issues. Maybe this will help? https://github.com/framer/motion/issues/1307#issuecomment-955877279

Since I can't replicate it, it's also impossible for me to say why you might be seeing this issue.

**Comment by EMCarlos** [comment]
> > Having the same issue, I'm using react-scripts v4.0.3 and getting the same error on the react-intersection-observer v9.1.0. Tried to upgrade to v9.3.3 but still happens:
> > `Failed to compile.`
> > `./node_modules/react-intersection-observer/react-intersection-observer.mjs` `Can't import the named export 'Component' from non EcmaScript module (only default export is available)`
> > OS: Windows Browser: chrome Version: Version 102.0.5005.115
> 
> Just to be clear - You got this with `react-intersection-observer` version 9.1.0?

That's right. 

> As far as I can tell, this issue is most likely caused by the Create React App environment you are using, and seems to be a > common issue other libraries are running. This library should be exposing the output files in the correct manner, that various > build tools can parse...

It only happens with this library, and one solution is to delete the .mjs file and it doesn't happen anymore. But I know that it is a temporary solution and that it will appear again.

**Comment by thebuilder** [comment]
If this error also occurs in `9.1.0`, then the errors is not caused by switching to `.mjs` for modules - Version`9.1.0` is not using `.mjs`, or the `exports` field: https://unpkg.com/browse/react-intersection-observer@9.1.0/package.json - This invalidates the [CRA bug](https://github.com/facebook/create-react-app/issues/10356), since that is caused by the `.mjs` extension.

I'll need someone to create a minimal example repo where this error occurs - If it is just CRA with `react-intersection-observer`, then this should be simple to configure.

**Comment by fedelernerldp** [comment]
I started having this issue today. It happened both in 9.1.0 and 9.3.3.
I tried using **_9.3.4-beta.2_** and it compiled correctly without errors.

**Comment by thebuilder** [comment]
> I started having this issue today. It happened both in 9.1.0 and 9.3.3. I tried using **_9.3.4-beta.2_** and it compiled correctly without errors.

It "works" because it selects the `"./react-intersection-observer.esm.js"` file. But since this file use `import/export` it should be called `.mjs` for proper Node support (and to follow the correct spec).

**Comment by thebuilder** [comment]
Okay - I tried running `react-scripts: 4.0.3` with `react-intersection-observer: 9.3.3` and seeing the same error.

* `react-scripts: 4.0.3` breaks.
* `react-scripts: 5.0.0` works.
* `react-scripts: 5.0.1` works.

If that's the case, then the problem is you are running the old version of `react-scripts`. You should upgrade to the latest version of `react-scripts`, or stay on an older version of `react-intersection-observer`.

If you can't, then you need to implement `.mjs`support in webpack - See https://github.com/framer/motion/issues/1307#issuecomment-955877279 for an example.

**Comment by fedelernerldp** [comment]
Thanks for the info!
Which version of react-intersection-observer is compatible with react-scripts 4.0.3??

**Comment by thebuilder** [comment]
I'd say `9.1.0`. Make sure to make the version specific, so it's `9.1.0` and not `^9.1.0`.

**Comment by thebuilder** [comment]
I've reverted to `.esm.js` in the `modules` field for now. This allows the various bundlers, including CRA 4 to import it.
