### ISSUE TITLE
infinite loop caused by `isInViewRef`

### ISSUE THREAD

**Issue by jjenzz** [thebuilder/react-intersection-observer#572]
When calling `setRef` from this package, it causes an infinite loop if called from within an inline function e.g. when passed as a param to packages like `react-merge-ref`.

Here's a simple repro of the issue (calling manually from inside an inline ref callback):

https://codesandbox.io/s/sweet-rgb-6werdb?file=/src/App.js

When an inline ref function is used, [React will set the ref to `null` and back again](https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs) on every render. So, from my quick dive into this package's code I believe this caveat is causing the `observer` to set up again [which is firing `setState`](https://github.com/thebuilder/react-intersection-observer/blob/master/src/useInView.tsx#L70) and re-rendering, which calls `setRef` with `null` (and back again), and loops.

**Comment by thebuilder** [comment]
Hey @jjenzz, see the [FAQ](https://github.com/thebuilder/react-intersection-observer#how-can-i-assign-multiple-refs-to-a-component). If your application code also needs access to the `ref`, then you must make a stable `useCallback` function.

There's no perfect way to solve this (that I'm aware of) - The library needs to use the callback ref function, since this is the only way it can correctly determine when the `ref` is set/changed. 

Valid use cases I've seen include:

- Not setting the `ref` on initial render (maybe a spinner is shown)
- Removing the `ref` after initial render
- Moving the `ref` between elements
- Toggling the `ref` based on UI state

All of these require the IntersectionObserver to be recreated, to correctly determine the new state.

**Comment by jjenzz** [comment]
> There's no perfect way to solve this (that I'm aware of)

The lib is calling `setState` with a new object reference regardless of whether the value has actually changed (causing an infinite loop). Checking `prevState` there would prevent it:

https://codesandbox.io/s/epic-pare-2d9w9j?file=/src/App.js

**Comment by jjenzz** [comment]
> Is it safe to use batching/`setState` instead of the `useCallback` for handling `ref`? Or any caveats to be aware of?

All safe as far as I know. A callback ref expects a function and `setState` is a function after all.

**Comment by thebuilder** [comment]
Seems to be causing quite a few extra renders - You already get two because of `setState` when the initial inView is set.

I've tried updating the callback, so it compares the entry with previous entry before updating state.

```js
(inView, entry) => {
  setState((prevState) => {
    if (!mounted) {
      mounted = true;

      if (
        prevState.entry &&
        prevState.entry.target === entry.target &&
        prevState.entry.isIntersecting === entry.isIntersecting &&
        prevState.entry.intersectionRatio === entry.intersectionRatio
      ) {
        // Hook has previously been used. Don't update the state
        return prevState;
      }
    }
    return {
      inView,
      entry,
    };
  });

  if (entry.isIntersecting && triggerOnce && unobserve.current) {
    // If it should only trigger once, unobserve the element after it's inView
    unobserve.current();
    unobserve.current = undefined;
  }
},
```

It's kinda working, but if you are scrolling slowly on the page, it will trigger multiple updates since the `intersectionRatio` keeps changing. In general this approach will cause the `entry` to be incorrect. It might be fine, but if a consumer is using specific values (like `time`, `intersectionRatio`, `intersectionRect`), then it becomes unreliable.

It will also recreate the IntersectionObserver on each render, instead of reusing it the instance - Would have to make the cleanup function lazy, which is going to cause extra headaches with async timeouts.

**Comment by thebuilder** [comment]
Tried with batching `setState` instead, and that seems to be working nicely. But it is triggering 3 renders, instead of 2 when mounted. Will try it out some more. 🤞

**Comment by jjenzz** [comment]
are you in `StrictMode` on dev when you see 3 renders?.

**Comment by thebuilder** [comment]
> are you in `StrictMode` on dev when you see 3 renders? React will trigger an extra render in this case on purpose.

No, StrictMode would double the renders. You can see it in your [CodeSandbox](https://codesandbox.io/s/dank-fog-4wm5cf) (updated with the changes from the PR) 

The following happens on every mount of the Hook:

1. Initial render, set the `ref` on HTML element 
2. State updated with `ref`
3. Callback from `IntersectionObserver` with a new state

**Comment by jjenzz** [comment]
> 1. Initial render, set the ref on HTML element
> 2. State updated with ref
> 3. Callback from IntersectionObserver with a new state

Ah, yeah that makes sense, there's not much you can do about that tho with this approach.

**Comment by heikomat** [comment]
I'm a little confused about the number of initial renders.
In the PR, a commit switches from `useCallback` to `useEffect`, a later commit reverts that and another later commit undoes that revert, so that `useEffect` is used.

Does that mean that we have to live with 3 renders on mount, or was another solution found, that results in 2 renders on mount, even with the useEffect?

Am i misinterpreting something here?

**Comment by thebuilder** [comment]
It's doing 3 renders at the moment. I tried different solutions, but the others still had issues. So ended up with useState
