### ISSUE TITLE
Flickering Point ⚛️

### ISSUE THREAD

**Issue by guaiamum** [thebuilder/react-intersection-observer#575]
# Context

Hey, love the lib, used it a couple of times already, but have faced this issue in a few implementations...

# The issue

Seems to be toggling `inView` on and off forever in a given scroll point (not hard to get to, actually), even though scrolling has stopped.

# Reproducible at:

[this codesandbox](https://codesandbox.io/s/sticky-cta-intersection-observer-5g963e?file=/src/StickyButton.tsx)

# Evidence:
![rio bug..](https://user-images.githubusercontent.com/21321095/179830868-02293ee2-d7b0-42f0-ad1f-fdf4d9b35c7c.gif)

**Comment by thebuilder** [comment]
You must use `trackVisiblity` and `delay` together.

https://github.com/thebuilder/react-intersection-observer#intersection-observer-v2-

**Comment by guaiamum** [comment]
> You must use `trackVisiblity` and `delay` together.
> 
> https://github.com/thebuilder/react-intersection-observer#intersection-observer-v2-

Right, the issue is not related to delay, though. In the gif above you can see even taking it out, the issue persists, but it’s so fast you can actually see both true and false

**Comment by thebuilder** [comment]
Fair enough - Had a look at the code sandbox. You're changing the `position` of your button from `fixed` to `sticky`, which causes the `<div>` with the `ref` to be moved below the `button`, thereby leaving the viewport, causing it to revert to position `fixed`, so goes back into view, etc... 

You need to ensure the layout is stable - especially if you're using `threshold: 1`, since it'll trigger as soon as any part of the element leaves the page. You could fix it by adding a wrapper with the size of the button/content:
https://codesandbox.io/s/sticky-cta-intersection-observer-forked-ksp5fv 

```jsx
export default function StickyButton() {
  const { ref, inView } = useInView({
    threshold: 1
  });

  return (
    <div ref={ref} style={{height: '46px'}}>
      <button
        type="button"
        className={clasnames("button sticky", { fullWidth: !inView })}
      >
        STICKY CTA
      </button>
    </div>
  );
}
```
