### ISSUE TITLE
The delay property doesn't apply when the element is already in view on reload.

### ISSUE THREAD

**Issue by IDrumsey** [thebuilder/react-intersection-observer#591]
**Describe the bug**: When I reload and the element is already in view, the delay property doesn't apply.

**To Reproduce**: https://codesandbox.io/s/agitated-ully-ccfz6v?file=/src/App.js:414-3926

**Expected behavior**

When reloading and the element is already in view, the delay property should still apply the same as if scrolling.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 107.0.5304.107

**Extra notes**: Go to the code sandbox and scroll down. Notice that the delay waits 3 seconds as expected. Now go into the HTML and remove the section indicated by the comments. Reload the sandbox iframe. Notice how there is now longer a delay even though it's configured for 3 seconds.

**Comment by thebuilder** [comment]
This is how the browser spec implements `delay` - The IntersectionObserver gets its initial state regardless of the `delay` property (otherwise you would also end up with an unknown state for the entire `delay`). 
`delay` is intended for use with `trackVisibility` (to minimize updates), and not as a way of delaying "animations".
