### ISSUE TITLE
InView Component Doesn't Trigger onChange After Updating to Latest NextJS Version

### ISSUE THREAD

**Issue by meedwire** [thebuilder/react-intersection-observer#649]
**Describe the bug:** 
After updating to the latest version of Next.js (13.5.6), the InView component from `react-intersection-observer` (version 9.5.2) stopped triggering the `onChange` event. This issue is occurring in a MAC M1 2020 environment, with Node 18.

**Expected behavior:** 
I expected the `onChange` event to be triggered normally as in previous versions of Next.js.

**Desktop:**

- OS: macOS M1 2020
- Browser: Chrome, Safari;
- Version: latest

**Comment by thebuilder** [comment]
Related https://github.com/thebuilder/react-intersection-observer/discussions/647

**Comment by thebuilder** [comment]
Is this using the the App Router? Can you reproduce it on a https://stackblitz.com/ Next.js starter?

It works fine in Pages Routers, running 13.5.6.

**Comment by meedwire** [comment]
> Is this using the the App Router? Can you reproduce it on a https://stackblitz.com/ Next.js starter?
> 
> It works fine in Pages Routers, running 13.5.6.

Yes, using App Router, I will create a reproduction.

**Comment by andekaizat** [comment]
Having the same problem using the App router with the latest package version & nextjs version

**Comment by thebuilder** [comment]
I'm not using App routwr myself. You are very welcome to dig into what might be the cause. Is it not flagged correctly as a client component?

**Comment by thebuilder** [comment]
If you are reporting issues like this, please [use the issue template](https://github.com/thebuilder/react-intersection-observer/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) - It's there for a reason. Just saying something isn't working is not helpful. At least provide the error message (which in this specific case, actually tells you exactly what the problem is)

I've now configured a Next application to test this, and the error message i get is very clear - It seems the issue is that Next.js is no longer detecting the `use client` directive. 

Running Next.js `13.4.19`, everything works as expected. 
Demo: https://stackblitz.com/edit/stackblitz-starters-bygtm1?file=components%2FObserver.tsx

Upgrading to 13.5.1, and it fails with:
![billede](https://github.com/thebuilder/react-intersection-observer/assets/3764345/47353bc3-f4c7-4b07-88ef-151e3ab9002b)

``` 
Error: Attempted to call useInView() from the server but useInView is on the client. 
It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
```

Demo: https://stackblitz.com/edit/stackblitz-starters-ubcjsa?file=package.json

---

For now, you can solve it by adding `use client` to your consuming component files.

**Comment by thebuilder** [comment]
Thinking about this - Shouldn't you define `"use client"` in a component that consumes `useInView` or `<InView>`? It would be pointless to have the observer, if you don't consume it. 

For reference:
- https://nextjs.org/docs/app/building-your-application/rendering/client-components
- https://react.dev/reference/react/use-client

**Comment by thebuilder** [comment]
After consulting with Vercel, I'm going to close this issue.
It's my understanding that it is intentional that you are seeing the error, because you are using a client feature inside a server page. 

Add `'use client'` to your page if you're relying on `<InView>` or `useInView`.

**Comment by thebuilder** [comment]
Dug a little deeper, and it seems like there is actually an issue with the `<InView>` component not triggering. It would have been helpful if this was included in the bug reports.

Still not sure why it's failing in Next.js all of a sudden. Needs more investigation.

**Comment by Echelpoel** [comment]
Thanks @thebuilder!
