### ISSUE TITLE
Upgrade to 9.5.4 and broke my compile.

### ISSUE THREAD

**Issue by rocklee889** [thebuilder/react-intersection-observer#660]
mode_modules/react-intersection-observer/index.d.ts(180,23): error TS1005: ',' expected.
18:21:27 node_modules/react-intersection-observer/index.d.ts(180,48): error TS1005: ',' expected.
18:21:27 node_modules/react-intersection-observer/index.d.ts(180,80): error TS1005: ',' expected.
18:21:27 node_modules/react-intersection-observer/index.d.ts(180,106): error TS1005: ',' expected.
18:21:27 node_modules/react-intersection-observer/index.d.ts(180,137): error TS1005: ',' expected.

Error code follows:
export { InView, type InViewHookResponse, type IntersectionObserverProps, type IntersectionOptions, type ObserverInstanceCallback, type PlainChildrenProps, defaultFallbackInView, observe, useInView };

node: 14.16.0
typescrpt: 4.3.5

**Comment by rocklee889** [comment]
Yesterday, everything worked fine.

**Comment by thebuilder** [comment]
Breaks because the it exports the types with `type`. This is supported from TypeScript 4.5.5. Not sure what caused this change. Might be tsup update? Doesn't say in the changelog.

Can you upgrade TypeScript?

This [playground links works](https://www.typescriptlang.org/play?ts=4.5.5#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAMozIxsC8cAbzpwRcYADsAasCwB3AFxwARhAgAbHOPqi4WcTChMA-IoCS+rFFRZ8wCOIDyS61ABulgKL7D9AL70AegQEYQBiUMw9ABNLODBiMFQGOAAVCDgAV2s4GAALNgADAB5zaTkAPgK4XBJIcT0YABo4JggMuLR0YHhkOAIM8Vt7ADo4U3hZYDU1ZTZcZGmsKOFZfPr3KBz8uFQuHmrc5HEAcyxUZsm8rbZ62ThXBYy2CAI4Aoky2QLR8xQoqO6dnEOXSeSwwneUhkXziCWauFyUyilGBC1Q6UouCwwHcKDelAIVTy3B2uTaaiisx2WHg9muwhq+mQEgkxzgABEHABZXQaEANUYpRFddBg3lYfn6LYksXmHhWGwwIFOFwbOCTabCED2brQYbJUyvVrtepLMRNFptapHFBqdEoXBY1Ci-LCADaBTllmsQ0czksGy8BiYBQAugAKXIwGCJeQBAIxdxqCCsKDDbUALymamQw2gxwCegAtABVdgJiC4VABADqWCUAQAggAFUwBL0K30qgOebxMACUwjpBQahgKzWOONZlvaeCdovSCxmYpiXCm6GQKgy8DFuAyUBR8Ak8p9Svswl23Cw+ohBQKACtUAAPYSgSCwQRjKFyOC+PrEUgKCoGAi2Pb1FSBIsIH9NxLFoZJGV2OAAGFansBo4H4cN+0w8o4HDYQSm-WRymEARwwEMRiOaAlmlHJhfxw3g8IInQRCKAFXDgAleAEAlfFItjRCKXIACZygEAoAAkcBiTYJFQYAYnuaF33gAASAQPmhXxhgKXwigCMTBLYwzOJMkR+18Qj22IwT+3oYQsCfNS4BiAhkAyNR4FQ8B0P0bQ7wKZJwjgZscwkA4kRRZIAE0rXmYEwE6FBxAYrA+QwmBQW2YpSmhOAAkqZojkpbp1WzOBDnEKINGqShuGnMEVigZAwDAadOR5DKJQFOBG3+PFqtq2JsuuN57GQ6rTiqfk8ggKISpq6p7AMdR6R2PY2Ei41NggWRgRqPz6n0UZGzS3QnwMXp4hTdBjT+Skxryuyqg1GYlHBDpnTNMaxSklIuQAGXFSULSXfbpwe6wd1y3Ac2dAA5ZB+XHN5diYDQ0ZpXAbzeO9HxfMQ-I-Sj8p-P8iBIcgGvwUCLE7M9xCgmCNnghl7CQ3y6gwrCmJYwjybuNBeAAIk40W4Em6asF48NtLkOi+35lbxHRDRhmTY5wzIcxXGheQyGaBXZCswSRPE8LmUOxEKRRFBKFtWRkCYdAUTkpZRhLbJpaOU4QTgbVxF1TZLx4YZDOMmyhfsxzLtc9zPO8lC0JOmBArvYQEACOgYnh5BHfz50v0+S6eBq9BsDwGBhm5-yYCIk8IPsbtYKgZsEnQAAfMKIvEKbor0Du7uaTgrzwoQdEQgwMnwaBw1u2MvybrtWcsYfEjgHurYkAe7aHzuHOEUQjp5-R2SUrk2n0bDFFcCAlO0E-U4aC+ohLMAoivBfKFcDfUDMAzU8yo17t0PnfB+UQn4iFPvXGs2YSziG1AMGAt97iQOgXAcQC0sCKA8JlKUPdxBeTUJggA+gMaCqosDISUIocM2FcLoKUjhIhJDMFUJ7IjHBaD76P2PiISha9eEYIEVVUqGhuExHodgmIJg4D4N6oQrBJCVZ8KgWI4aGgpp+1wfhE2igVDqE0ErYMgCV5M1boGZWTD1GYPdpYNBVd8DDGcTAKRWA-AMCCCERAkRq5wCkqoAA1ugEAyBgnbXgDgVADExpBxDuNSEnwqhh2eEaNomxYFp1QKMZCS4s5JKyFgIWVQyQQGCRVK4YpwwpiZgsHCbo6lAlQBGUIzTOY4QeqaKIPwJjZkKZQGA+5USogPC7VWa5g4nDxAUAkaMxTJOhKkvYWRUpPW2HuA8DRCkenomGSM0ZYzxkTBlFMlh0wQCzNMXM+ZCzMzLBWKstZ6xNlbLZCxIDqFQCDIYfs+o-GNmdMAY4wJFnzIDmKLqoMMIPWdlKeJOpspQCWhstg5TKnvUGVgVyYow5ZABb4pAAABZyKMwAaEKUFQmhS3zQHgG4-81MgLV3gn4ulpNMjWCFr+JlgFaYgTAozSCnC25sqJarLmL8pR8yYZPJAMDObwEorRKinxTGGF5fwYpQsKKFKEnkSgqAyQUkUAABkaPqxi2gJUiCGSM-CVr2KcW4lgAgvF+KCQVaZYykkZLIDklRRSyl9ZyFcppE2ul9KR3Ek6uAZkcRetEEfPx-gqWZ0QDnPOOZHb9EGEzLlJTiIUS2Eak1i03IZRds0a6uBgnSEUkoKY3QmA0VUDALkBdJziDbRAC0BgQWnCgA4QYWBmioGCcAMAxtg5KgWELZoHlphKDwMEhdUt+4y2aL4eRHZgEtzAEzVA-ZAGfCCRU7AqA6jWEcj4wpNZDjwGNeSSkn1xqJy8vAT6hx9bQDEK8WUQDm5+m+WIdAAxUAZHavSpYRhCmmBiEuOJ2xIBqCYAQSqhx0CfT0HAZMAaljNAeolcRuIxQEHUMmSYMzDjtT0PIQpRY3gDHchIJYBRFBCmIMLYElhiBQEY28GeWAqh-oKEu6wHGOA0iSSbKoDw1BPEhcKV1xwC4jWLi8Kiny6RpMKcELNNgc1sDzb6StHlP0ADElwrrrbqgxyhVAaBtD3Fjbq2NRBPcwjRd6-HEuSq1UgPUwZwCY9CxRIWxqivcIU-zBcUbWmXau0LKEbPJdMwWv6UBB2xFWLhoV+7gT4vQAiXRSQ-MBYSx0tWKW93AbgFY2I1Xysksq6QJdahbNruIil6zSW61qoKgpp4hK4DEvtVAYElmBhmaY8hZzxCwB9Bm5lx9pIX1UgHccIdv10gDEoJOXYo1tjRcsFnQz+dc0raBFLYRwWGh4IIRaeY-XgmKEa1Acwl5R35Ne80Zru6gOr2+eYboi60t2eIvIoxC2t6ZBqu5+onn6FqNEYwFgbAHAgG6EUFIzQADSZdojoEia0V4KQ8L8GbMAOtuPmgeCfPDDIMQiik603juA+PyjlHoMwVgDXQFfa4D9iHlSsIOZhyY3QfZzHgWBz2H5NjmLefoEKjyWJIgI7AXdQQYiJdOc0Jg+isvhUt1Ab8hirmEcYaR-Yt1ig3GuLdU4e8ioihHCYHhHuDDZFYHkRFjCbDpio5YV4tXeA2B1a7IelpROK7Lzl5YwXs7dc6B8akbYUek+gfD1iMgbtZJQXEGh-E7aqiL0sMwMQMR9DAAw2ccaAepR-vZJWDIIXVgQGyFuePBc2AGBwDwSkaBxo94BDMlQT4pYAe2KG2QrkKObDFPdqUqwae5DA+NU7UB885C7TSH4M-CjED7VUYA6BiHTBrWsUf18ojoC02KauGQFhuTbyFufrk++Ft6dnMRJ+YB-cns4dL9SExF09O0oBu0HY79xoAC8kbQf02BhsG9FJscc1lM2BkJ2B2BA4u1IoK9YBW1dBhhjhRgCgABGM1MAKfUSagqfAAZnoLgAABZ6Cqhwxspp1uIQUoxmgVBowSBmgNACAYB-lM1-921IDu15FdhssThMF09EZ29PpNhPoYBZAsBcMCgzUqhSo3gKCz8aoadGoZkxRUwsQmR-ZiQn0yQvJX1kDz9gAlA6pPpF9+9stttLBWQEDUQ7R0g30bQCgC5WoQxp8VEQBVDzgA5cAGp9gQBP0p06otsh04gH59BckJCdBDUzhy15FiFIjYg2FCioA3RQxFDggGti84lPDUixQTZEtOtkt7ANc-9sjajLAR0sRocDcjgKikB2BJ0ltOgQVpk2QxRt9MD8Q3Uqg2jRAJ0p0ejjE+jwDKj2AZN6jZ1gBX8UDwjFk5NHNljxBBQVMSM31ikyoMl2hnJWB8BxoV8dwAjtowVZ9VJ6UA5LwPxLhchUUZx1QjhHicgOjQ4SAaREQZk8tgRypnN3BMi5iRAWQ501AhYliFt+i4A+smiBs-oVMGi0l-1xos8vkFdN8IMoM1JCN1k8RUN0NKpnZUBxAyB4B8MYhKR4S+hRcUTDFeitBVikAiSzdQNXBRIUsUhWpsTthn8dinCm01AW09jtgHisjRBa160ZTm1mBUTDc+SE9TcQMSThSUt1iehA4WQEjSAYgcwGJ1DNDcNsElQMN5gj1lSRBLSXZ8iVDLB0TftlwVMMsbtISsA1RNiVIfx8TSsTgG92TfZIz5F5ZiJuSjiNUmATdCsPsLcQ8NFrJc9I8gds8Fd-44979dS0yY9OZU9RBfMdAkA95kRcMbjFQNxlt80bsbDXUsQcQG8bRoJXd8AxE-FGQplUo3gDjJcbR9C5kZjpRbCNtPp+ykARjQVdt7jgD4D5yc4p5bY6zxB6F68KQAFNc5J-4VZHc3EPEvFfMkAUgMd0Ar0bA68acpid5N1B5gQHF5C2QtMhZ9Mc4+c2BnzayURCz+ABTHAyyasAAyCsmBLclEeRU84Cc8vk+cw847NgWQVqdqacJUkfPIc-GFU6FCoUfCnpBcKkG0Y8eQxSXAAimuFCw0P4+FQE4pPEPcXYamB45oClGJNgFisUHVYiFCjFAOcJcQZAaw7YAkeOOU3AboNDAFassbD9ZOAoMgTiMgYKNidktAeRNnV4AAKXYAAA1hg5QqKacm8YBUBvSlwth8L-S6RAzgzthIo59NorwDgysXSN0dFYz6F9ckzpczESzgN0ylc8I7E6A-woKsccdHcAZgZ-4igEqgZLLyhmgyAYzTgyAec6BLyM82Bz1KkjVr02BINoNYBsM+0N8QiJl9CezFRK05DZ4lQThzt0d+chYirL1SrMI4A3QxFwxfcgClF4Ag81BMzLUdAxye0xFQKwrgw4c3Mbclg6BQw4AoLJ5RACQZEcERqQtxrMzMEAq0SxF6JAcdN9S24Lc-BHIbj3iyZqIcgMcS5oRuqzhSqa0Xr5rQF-4vrOq8zlRwLoi-yBcQc1ZhcsQfSut-r-y+5AKD4R5zMk4YBMSut11TtmgBLS400gA) work the build output. Downgrade, and it throws that warning.

**Comment by rocklee889** [comment]
Thanks !  @thebuilder 

Upgrade to typescript 4.5.5 this problem is solved
