### ISSUE TITLE
index.d.ts file seems causing typescript errors

### ISSUE THREAD

**Issue by SudharsanSukumar** [thebuilder/react-intersection-observer#98]
Hi,

I recently updated to v6.1.0 from v5.0.3 and noticed that the index.d.ts file seems to be incorrect which causes typescript build errors. When trying to use the default import it comes back as undefined. (import Observer from "react-intersection-observer")

Worked around it by doing:
import * as Observer from "react-intersection-observer" <this how we get the import to work>
import { IntersectionObserverProps } from "react-intersection-observer" <needed to get around index.d.ts>

const WrappedObserver = (Observer as any) as React.ComponentClass < IntersectionObserverProps >;

Now typescript will allow us to use Observer as usual.

return(
  < WrappedObserver />
);

Thanks!

**Comment by thebuilder** [comment]
Hey - thanks for the heads up. I'm not using the typescript definition file myself, so I might very well have messed something up. Feel free to make a pull request if you have a fix! 🙏Otherwise I'll try to have a look at it.

**Comment by SudharsanSukumar** [comment]
Sorry but I don't have a good fix. Luckily I don't think it will be too bad. I'll try and help if you need any.

**Comment by thebuilder** [comment]
What is the exact TypeScript error you get?
I've tried to set up a sample file and it seems to be working fine:

```typescript
import * as React from 'react';
import Observer from 'react-intersection-observer';

function render() {
  return (
    <Observer threshold={[0.1, 0.9]}>
      {({inView, ref} )=> <div ref={ref}>{inView}</div>}
    </Observer>
  );
}
```

I did notice an error with the type for the `ref` prop in the render prop function, that i'll publish a fix for.

**Comment by fpapado** [comment]
@SudharsanSukumar, I've been using the TS definitions without errors for a few months now.
The "default import is undefined" is usually a `tsconfig.json` issue, rather than a definition issue. Out of the box, Typescript does not handle default imports the same way as, say, Babel, which is why you have to use the faux namespace (`* as...`) import.

However, there is a `tsconfig.json` option to specify this:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
    // Other things here as you wish
  }
}
```

Fwiw, I tend to use this in all my projects, since it's less special syntax to remember :)

Here's a demo showing the default import, as well as types import:
https://codesandbox.io/s/w60m8plq3k

(Looking at the history, the definitions always had a default export, so I can't see anything relevant changing from 5.x to 6.x. Is it the same project that you updated in?)

The TS2.7 notes have a good explanation, under "Support for import d from "cjs" form CommonJS modules with --esModuleInterop":
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

**Comment by thebuilder** [comment]
Seems like you can solve the issue by configuring Typescript. I'll close this issue for now.

**Comment by SudharsanSukumar** [comment]
Thanks for the explanation I'll give that a shot later today!
